# Generated by Django 5.2.3 on 2025-06-28 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('number_of_guests', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[(datetime.time(7, 0), '7:00 PM'), (datetime.time(8, 0), '8:00 PM'), (datetime.time(9, 0), '9:00 PM'), (datetime.time(10, 0), '10:00 PM')])),
                ('seating', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('none', 'No Preference')], default='none', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonApp.category')),
            ],
        ),
    ]
