# Generated by Django 5.2.3 on 2025-06-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='unique_date_time'),
        ),
    ]
